### PR TITLE
Fix webpack

### PR DESCRIPTION
**Pull request by tontonAurel**

### CODE REVIEW

**Comment by uyson** [comment]
+1

**Comment by mathroc** [comment]
+1 builds on ci seems to have failed because of a problem with saucelabs, can someone restart the tests on travis for this PR ?

**Comment by elmariofredo** [comment]
+1 seems to be problem with Sauce Labs credentials. Tests are passing on local.

**Comment by elmariofredo** [comment]
@tontonAurel I would suggest to rebase your changes on current master, which would trigger new CI build and then @ocombe would hopefully have easy choice to merge it.

Thanks!

**Comment by ocombe** [comment]
Sorry that's my fault. I need to get back into this project sometimes but I don't really have the time right now.
Also CI is broken for PRs because of sauce labs (I don't know why, probably a config problem).

**Comment by elmariofredo** [comment]
Thanks @ocombe!

p.s. It seems that sauce labs now require to set `username` and `access_key` as per docs https://docs.travis-ci.com/user/sauce-connect/#Setting-up-Sauce-Connect 
Just for future reference not pushing ;) I'm sure that you have lots of other better things to do.

**Comment by elmariofredo** [comment]
@ocombe can we release this merge request pretty please :)

**Comment by MrJuliuss** [comment]
+1, need a release :)

**Comment by de-luca** [comment]
+1

**Comment by scotttrinh** [comment]
I'll take a look at getting this merged correctly, if it hasn't already been handled. Stay tuned!

**Pull request merged**
