### PR TITLE
fix: Always remove $$hashKey from object or array objects

### LINKED ISSUE #137: $$hashKey is now being saved on setitem
On a commit (https://github.com/ocombe/angular-localForage/commit/6a42de381e6969a13dfac07e2e04f1b9cd806b3a, line 125), the angular.copy() is removed in favour of angular.extend({}, value).
The commit message states the $promise value is still removed.
But the **$$haskey** property is still copied on arrays. [Cause similar to mine](https://mutablethought.com/2013/04/25/angular-js-ng-repeat-no-longer-allowing-duplicates/])

Can this be resolved within the plugin, or is a workaround more suitable for this?

Example:
value = [{**$$hashKey**: "object:70", Title:"Dummy"}, {**$$hashKey**: "object:71", Title:"Dummy2"}]

_angular.copy(value)_ gives:  [{Title:"Dummy"}, {Title:"Dummy2"}] 

_angular.extend({}, value)_ gives: [{**$$hashKey**: "object:70", Title:"Dummy"}, {**$$hashKey**: "object:71", Title:"Dummy2"}]

### PR DESCRIPTION
**Pull request by scotttrinh**
This doesn't deeply recurse into objects like `angular.copy` did, but we don't want a performance regression.

Fixes #137

### CODE REVIEW

**Comment by scotttrinh** [comment]
@BMarinos

Just added the recursion. Do you mind just sanity-checking it for me? I'd like just a second set of eyes on it.

**Comment by scotttrinh** [comment]
Ugh. This is mutating the original value if you pass it an `Array`. More work to do!

**Comment by BMarinos** [comment]
You JavaScript looks advanced, so respect for that.
I wonder, what if obj is an array in the StripMeta function?
For example `localCopy` is `[[]]`?
I created a jsbin with a few test examples: https://jsbin.com/zulacebopo/edit?js,console

**Comment by scotttrinh** [comment]
Code review works! Excellent point. Refactoring now.

**Comment by scotttrinh** [comment]
@BMarinos 
Moved the logic that checks if the value you're saving is an `Array` or an `Object` into `stripMeta` and invoked that directly on `value` in the `setItem` method.

You'll see in the `stripMeta` method that it does the same check that used to live in `setItem`, but now in the `else` case (which is just the final `return` statement), it just returns the `value` if it isn't an `Array` or an `Object`. Added an `Array` with a bunch of different types in it (including an object with a `$$hashKey` entry) to the tests.

Let me know if you see anything else! Thanks for the second set of eyes!

**Comment by BMarinos** [comment]
Looks like it works correctly now :)
It is even tested thoroughly.

One optimization: the check wether it is array or object is only required once, I think. [[JSBin (stripMeta3)](https://jsbin.com/xejizukoki/edit?js,console)]

```javascript
return Object
  .keys(copy)
  .reduce(function stripEntries(acc, key) {
    acc[key] = stripMeta(copy[key]);
    return acc;
  }, {});
```

**Pull request merged**
